lines <- readLines("src/models/q_learning_ddm_dynamic.stan")
text <- paste(lines, collapse="\n")
text <- gsub("real w_bias_t = 0.5 \\+ 0.45 \\* tanh\\(theta_ctx_s \\* iti\\[t\\]\\);", "real prev_rt = (t == start_t) ? 0.5 : rt[t-1];\n        real w_bias_t = 0.5 + 0.45 * tanh(theta_ctx_s * prev_rt);", text)
text <- gsub("real a_t = a_s \\+ beta_a_s \\* tanh\\(theta_ctx_s \\* iti\\[t\\]\\);", "real a_t = a_s + beta_a_s * tanh(theta_ctx_s * prev_rt);", text)
writeLines(text, "src/models/q_learning_ddm_dynamic.stan")

lines <- readLines("src/models/q_learning_ddm_dynamic_gq.stan")
text <- paste(lines, collapse="\n")
text <- gsub("real w_bias_t = 0.5 \\+ 0.45 \\* tanh\\(theta_ctx_s \\* iti\\[t\\]\\);", "real prev_rt = (t == start_t) ? 0.5 : rt[t-1];\n      real w_bias_t = 0.5 + 0.45 * tanh(theta_ctx_s * prev_rt);", text)
text <- gsub("real a_t = a_s \\+ beta_a_s \\* tanh\\(theta_ctx_s \\* iti\\[t\\]\\);", "real a_t = a_s + beta_a_s * tanh(theta_ctx_s * prev_rt);", text)
writeLines(text, "src/models/q_learning_ddm_dynamic_gq.stan")
