lines <- readLines("C:/Users/DCCS5/Documents/one_for_all/cerebellum_project/reservoir_model/m012_candidate.stan")
gq <- c(
"generated quantities {",
"  vector[N_trials] log_lik;",
"  {",
"    for (s in 1:N_subj) {",
"      vector[2] Q = rep_vector(0.5, 2);",
"      vector[4] frac_mem = rep_vector(0.0, 4);",
"      vector[4] Z = rep_vector(0.0, 4);",
"      vector[4] W_PC_latent = rep_vector(0.0, 4);",
"      vector[4] W_exp_s = to_vector(W_exp[s]);",
"      vector[4] inv_W_exp = inv_frac_alpha .* W_exp_s;",
"      ",
"      real v_s = v_ctx[s];",
"      real phys_a_base = 0.11 + 3.0 * inv_logit(a_base_raw[s]);",
"      real delta_max = 1.0 / phys_a_base;",
"      real tnd_s = tnd[s];",
"      real aw_s = aw[s];",
"      real al_s = al[s];",
"      real a_pc_s = alpha_pc[s];",
"      real inv_tau = 1.0 / tau_decay[s];",
"      real g_s = golgi_scale[s];",
"      real w_cb_s = w_cb[s];",
"      real w_ctx_s = w_ctx[s];",
"      real beta_mis_s = beta_mismatch[s];",
"      ",
"      for (t in start_idx[s]:end_idx[s]) {",
"        int ch = resp[t];",
"        real R = reward[t];",
"        real phys_decay = exp(-clean_iti[t] * inv_tau);",
"        Q = 0.5 + (Q - 0.5) * phys_decay;",
"        real Q_diff = Q[1] - Q[2];",
"        ",
"        frac_mem = frac_alpha .* frac_mem + inv_W_exp * Q[ch];",
"        Z = phys_decay * (kappa_vec .* Z) + tanh(frac_mem);",
"        ",
"        vector[4] W_PC_eff = 3.0 * tanh(W_PC_latent * 0.3333333333333333);",
"        vector[4] eff_z = W_PC_eff .* Z;",
"        vector[4] abs_approx = sqrt((eff_z .* eff_z) + 1e-8);",
"        vector[4] S_mask = tanh(g_s * abs_approx);",
"        ",
"        real cb0 = dot_product(S_mask[1:2], eff_z[1:2]);",
"        real cb1 = dot_product(S_mask[3:4], eff_z[3:4]);",
"        ",
"        real Cb_diff = cb0 - cb1;",
"        real M_align = tanh(w_cb_s * Cb_diff) * tanh(w_ctx_s * Q_diff);",
"        real caution = log1p_exp(-10.0 * M_align) * 0.1;",
"        ",
"        real a_dyn = phys_a_base + delta_max * tanh(beta_mis_s * caution);",
"        real veff_raw = v_s * Q_diff;",
"        real veff = (ch == 1) ? veff_raw : -veff_raw;",
"        ",
"        log_lik[t] = wiener_lpdf(rt[t] | a_dyn, tnd_s, 0.5, veff);",
"        ",
"        real pe = R - Q[ch];",
"        real alpha_eff = (pe > 0) ? aw_s : al_s;",
"        Q[ch] += alpha_eff * pe;",
"        ",
"        real alpha_E = a_pc_s * pe;",
"        if (ch == 1) { W_PC_latent[1:2] += alpha_E * Z[1:2]; }",
"        else { W_PC_latent[3:4] += alpha_E * Z[3:4]; }",
"      }",
"    }",
"  }",
"}"
)
writeLines(c(lines, gq), "C:/Users/DCCS5/Documents/one_for_all/cerebellum_project/reservoir_model/m012_candidate.stan")
