pacman::p_load(tidyverse, cmdstanr, posterior)
fit_q <- read_rds("results/fit_q_complete.rds")
fit_gating <- read_rds("results/fit_full_gating_complete.rds")
stan_data <- read_rds("results/stan_data.rds")
mod_q <- cmdstan_model("src/models/q_learning_ddm_gq.stan")
gq_q <- mod_q$generate_quantities(fitted_params = fit_q, data = stan_data, parallel_chains = 4)
mod_gating <- cmdstan_model("src/models/bvk_full_gating_gq.stan")
gq_gating <- mod_gating$generate_quantities(fitted_params = fit_gating, data = stan_data, parallel_chains = 4)
ll_q <- apply(as_draws_matrix(gq_q$draws("log_lik")), 2, mean)
ll_gating <- apply(as_draws_matrix(gq_gating$draws("log_lik")), 2, mean)

cat("Mean ll_q:", mean(ll_q), "\n")
cat("Mean ll_gating:", mean(ll_gating), "\n")
cat("Sum ll_q:", sum(ll_q), "\n")
cat("Sum ll_gating:", sum(ll_gating), "\n")
