pacman::p_load(loo, readr, cmdstanr)
stan_data <- read_rds("results/stan_data.rds")
fit_base <- read_rds("results/fit_bvk_complete.rds")
mod_base_gq <- cmdstan_model("src/models/bvk_continuous_gq.stan")
gq_base <- mod_base_gq$generate_quantities(fitted_params = fit_base, data = stan_data, parallel_chains = 4)
ll_array <- gq_base$draws("log_lik")
r_eff <- relative_eff(exp(ll_array))
loo_base <- loo(ll_array, r_eff = r_eff)
print(loo_base)
