pacman::p_load(loo, readr, cmdstanr)
stan_data <- read_rds("results/stan_data.rds")
fit_q <- read_rds("results/fit_q_complete.rds")
mod_q_gq <- cmdstan_model("src/models/q_learning_ddm_gq.stan")
gq_q <- mod_q_gq$generate_quantities(fitted_params = fit_q, data = stan_data, parallel_chains = 4)
ll_array_q <- gq_q$draws("log_lik")
r_eff_q <- relative_eff(exp(ll_array_q))
loo_q <- loo(ll_array_q, r_eff = r_eff_q)
print(loo_q)
